// 40 best Google APi fonts of 2018
// https://www.typewolf.com/google-fonts
// To find the file with all the fonts: https://us-east-2.console.aws.amazon.com/codesuite/codecommit/repositories/cms/browse/refs/tags/v0.8.92/--/related-data-json/google-fonts-api.json?region=us-east-2

export const googleWebFonts = [
  ////// FONTS STORED ON GOOGLE ////////
  {
    family: 'Rubik',
    format: 'truetype',
    category: 'sans-serif',
    variants: ['300', '300italic', '400', '400italic', '500', '500italic', '700', '700italic', '900', '900italic'],
    version: 'v7',
    lastModified: '2017-11-21',
    files: {
      300: 'https://fonts.gstatic.com/s/rubik/v7/iJWHBXyIfDnIV7Fqj1ma.ttf',
      '300italic': 'https://fonts.gstatic.com/s/rubik/v7/iJWBBXyIfDnIV7nEldWY8WU.ttf',
      400: 'https://fonts.gstatic.com/s/rubik/v7/iJWKBXyIfDnIV4nG.ttf',
      '400italic': 'https://fonts.gstatic.com/s/rubik/v7/iJWEBXyIfDnIV7nErXk.ttf',
      500: 'https://fonts.gstatic.com/s/rubik/v7/iJWHBXyIfDnIV7Eyjlma.ttf',
      '500italic': 'https://fonts.gstatic.com/s/rubik/v7/iJWBBXyIfDnIV7nElY2Z8WU.ttf',
      700: 'https://fonts.gstatic.com/s/rubik/v7/iJWHBXyIfDnIV7F6iFma.ttf',
      '700italic': 'https://fonts.gstatic.com/s/rubik/v7/iJWBBXyIfDnIV7nElcWf8WU.ttf',
      900: 'https://fonts.gstatic.com/s/rubik/v7/iJWHBXyIfDnIV7FCilma.ttf',
      '900italic': 'https://fonts.gstatic.com/s/rubik/v7/iJWBBXyIfDnIV7nElf2d8WU.ttf',
    },
  },
  {
    family: 'Exo',
    format: 'truetype',
    category: 'sans-serif',
    variants: [
      '100',
      '100italic',
      '200',
      '200italic',
      '300',
      '300italic',
      '400',
      '400italic',
      '500',
      '500italic',
      '600',
      '600italic',
      '700',
      '700italic',
      '800',
      '800italic',
      '900',
      '900italic',
    ],
    // "subsets": ["latin-ext", "latin", "vietnamese"],
    version: 'v7',
    lastModified: '2018-09-19',
    files: {
      100: 'https://fonts.gstatic.com/s/exo/v7/4UaMrEtFpBIaEH6m.ttf',
      '100italic': 'https://fonts.gstatic.com/s/exo/v7/4UaCrEtFpBISdkbC0DI.ttf',
      200: 'https://fonts.gstatic.com/s/exo/v7/4UaDrEtFpBIavF-G8A.ttf',
      '200italic': 'https://fonts.gstatic.com/s/exo/v7/4UaBrEtFpBISdkZu8RLm.ttf',
      300: 'https://fonts.gstatic.com/s/exo/v7/4UaDrEtFpBIa2FyG8A.ttf',
      '300italic': 'https://fonts.gstatic.com/s/exo/v7/4UaBrEtFpBISdkYK8hLm.ttf',
      400: 'https://fonts.gstatic.com/s/exo/v7/4UaOrEtFpBIidA.ttf',
      '400italic': 'https://fonts.gstatic.com/s/exo/v7/4UaMrEtFpBISdn6m.ttf',
      500: 'https://fonts.gstatic.com/s/exo/v7/4UaDrEtFpBIagF2G8A.ttf',
      '500italic': 'https://fonts.gstatic.com/s/exo/v7/4UaBrEtFpBISdkZS8xLm.ttf',
      600: 'https://fonts.gstatic.com/s/exo/v7/4UaDrEtFpBIarFqG8A.ttf',
      '600italic': 'https://fonts.gstatic.com/s/exo/v7/4UaBrEtFpBISdkZ-9BLm.ttf',
      700: 'https://fonts.gstatic.com/s/exo/v7/4UaDrEtFpBIayFuG8A.ttf',
      '700italic': 'https://fonts.gstatic.com/s/exo/v7/4UaBrEtFpBISdkYa9RLm.ttf',
      800: 'https://fonts.gstatic.com/s/exo/v7/4UaDrEtFpBIa1FiG8A.ttf',
      '800italic': 'https://fonts.gstatic.com/s/exo/v7/4UaBrEtFpBISdkYG9hLm.ttf',
      900: 'https://fonts.gstatic.com/s/exo/v7/4UaDrEtFpBIa8FmG8A.ttf',
      '900italic': 'https://fonts.gstatic.com/s/exo/v7/4UaBrEtFpBISdkYi9xLm.ttf',
    },
  },
  {
    family: 'Chivo',
    format: 'truetype',
    category: 'sans-serif',
    variants: ['300', '300italic', '400', '400italic', '700', '700italic', '900', '900italic'],
    // "subsets": ["latin-ext", "latin"],
    version: 'v9',
    lastModified: '2017-10-10',
    files: {
      300: 'https://fonts.gstatic.com/s/chivo/v9/va9F4kzIxd1KFrjDY8Z_.ttf',
      '300italic': 'https://fonts.gstatic.com/s/chivo/v9/va9D4kzIxd1KFrBteUp9sKg.ttf',
      400: 'https://fonts.gstatic.com/s/chivo/v9/va9I4kzIxd1KFoBv.ttf',
      '400italic': 'https://fonts.gstatic.com/s/chivo/v9/va9G4kzIxd1KFrBtQeY.ttf',
      700: 'https://fonts.gstatic.com/s/chivo/v9/va9F4kzIxd1KFrjTZMZ_.ttf',
      '700italic': 'https://fonts.gstatic.com/s/chivo/v9/va9D4kzIxd1KFrBteVp6sKg.ttf',
      900: 'https://fonts.gstatic.com/s/chivo/v9/va9F4kzIxd1KFrjrZsZ_.ttf',
      '900italic': 'https://fonts.gstatic.com/s/chivo/v9/va9D4kzIxd1KFrBteWJ4sKg.ttf',
    },
  },
  {
    family: 'Lora',
    format: 'truetype',
    category: 'serif',
    variants: ['400', '400italic', '700', '700italic'],
    // "subsets": ["latin-ext", "latin", "vietnamese", "cyrillic", "cyrillic-ext"],
    version: 'v12',
    lastModified: '2017-11-07',
    files: {
      400: 'https://fonts.gstatic.com/s/lora/v12/0QIvMX1D_JOuAw0.ttf',
      '400italic': 'https://fonts.gstatic.com/s/lora/v12/0QIhMX1D_JOuMw_7Jg.ttf',
      700: 'https://fonts.gstatic.com/s/lora/v12/0QIgMX1D_JOuO7HeBts.ttf',
      '700italic': 'https://fonts.gstatic.com/s/lora/v12/0QIiMX1D_JOuMw_Dmt5unw.ttf',
    },
  },
  {
    family: 'Source Sans Pro',
    format: 'truetype',
    category: 'sans-serif',
    variants: [
      '200',
      '200italic',
      '300',
      '300italic',
      '400',
      '400italic',
      '600',
      '600italic',
      '700',
      '700italic',
      '900',
      '900italic',
    ],
    // "subsets": ["latin-ext", "greek", "latin", "vietnamese", "cyrillic", "cyrillic-ext", "greek-ext"],
    version: 'v11',
    lastModified: '2017-10-11',
    files: {
      200: 'https://fonts.gstatic.com/s/sourcesanspro/v11/6xKydSBYKcSV-LCoeQqfX1RYOo3i94_AkA.ttf',
      '200italic': 'https://fonts.gstatic.com/s/sourcesanspro/v11/6xKwdSBYKcSV-LCoeQqfX1RYOo3qPZYokRdr.ttf',
      300: 'https://fonts.gstatic.com/s/sourcesanspro/v11/6xKydSBYKcSV-LCoeQqfX1RYOo3ik4zAkA.ttf',
      '300italic': 'https://fonts.gstatic.com/s/sourcesanspro/v11/6xKwdSBYKcSV-LCoeQqfX1RYOo3qPZZMkhdr.ttf',
      400: 'https://fonts.gstatic.com/s/sourcesanspro/v11/6xK3dSBYKcSV-LCoeQqfX1RYOo3aPw.ttf',
      '400italic': 'https://fonts.gstatic.com/s/sourcesanspro/v11/6xK1dSBYKcSV-LCoeQqfX1RYOo3qPa7g.ttf',
      600: 'https://fonts.gstatic.com/s/sourcesanspro/v11/6xKydSBYKcSV-LCoeQqfX1RYOo3i54rAkA.ttf',
      '600italic': 'https://fonts.gstatic.com/s/sourcesanspro/v11/6xKwdSBYKcSV-LCoeQqfX1RYOo3qPZY4lBdr.ttf',
      700: 'https://fonts.gstatic.com/s/sourcesanspro/v11/6xKydSBYKcSV-LCoeQqfX1RYOo3ig4vAkA.ttf',
      '700italic': 'https://fonts.gstatic.com/s/sourcesanspro/v11/6xKwdSBYKcSV-LCoeQqfX1RYOo3qPZZclRdr.ttf',
      900: 'https://fonts.gstatic.com/s/sourcesanspro/v11/6xKydSBYKcSV-LCoeQqfX1RYOo3iu4nAkA.ttf',
      '900italic': 'https://fonts.gstatic.com/s/sourcesanspro/v11/6xKwdSBYKcSV-LCoeQqfX1RYOo3qPZZklxdr.ttf',
    },
  },
  {
    family: 'Source Serif Pro',
    format: 'truetype',
    category: 'serif',
    variants: ['400', '600', '700'],
    // "subsets": ["latin-ext", "latin"],
    version: 'v5',
    lastModified: '2017-10-10',
    files: {
      400: 'https://fonts.gstatic.com/s/sourceserifpro/v5/neIQzD-0qpwxpaWvjeD0X88SAOeaiXM.ttf',
      600: 'https://fonts.gstatic.com/s/sourceserifpro/v5/neIXzD-0qpwxpaWvjeD0X88SAOeasasahSs.ttf',
      700: 'https://fonts.gstatic.com/s/sourceserifpro/v5/neIXzD-0qpwxpaWvjeD0X88SAOeasc8bhSs.ttf',
    },
  },
  {
    family: 'Roboto',
    format: 'truetype',
    category: 'sans-serif',
    variants: [
      '100',
      '100italic',
      '300',
      '300italic',
      '400',
      '400italic',
      '500',
      '500italic',
      '700',
      '700italic',
      '900',
      '900italic',
    ],
    // "subsets": ["latin-ext", "greek", "latin", "vietnamese", "cyrillic", "cyrillic-ext", "greek-ext"],
    version: 'v18',
    lastModified: '2017-10-16',
    files: {
      100: 'https://fonts.gstatic.com/s/roboto/v18/KFOkCnqEu92Fr1MmgWxP.ttf',
      '100italic': 'https://fonts.gstatic.com/s/roboto/v18/KFOiCnqEu92Fr1Mu51QrIzc.ttf',
      300: 'https://fonts.gstatic.com/s/roboto/v18/KFOlCnqEu92Fr1MmSU5vAw.ttf',
      '300italic': 'https://fonts.gstatic.com/s/roboto/v18/KFOjCnqEu92Fr1Mu51TjARc9.ttf',
      400: 'https://fonts.gstatic.com/s/roboto/v18/KFOmCnqEu92Fr1Me5Q.ttf',
      '400italic': 'https://fonts.gstatic.com/s/roboto/v18/KFOkCnqEu92Fr1Mu52xP.ttf',
      500: 'https://fonts.gstatic.com/s/roboto/v18/KFOlCnqEu92Fr1MmEU9vAw.ttf',
      '500italic': 'https://fonts.gstatic.com/s/roboto/v18/KFOjCnqEu92Fr1Mu51S7ABc9.ttf',
      700: 'https://fonts.gstatic.com/s/roboto/v18/KFOlCnqEu92Fr1MmWUlvAw.ttf',
      '700italic': 'https://fonts.gstatic.com/s/roboto/v18/KFOjCnqEu92Fr1Mu51TzBhc9.ttf',
      900: 'https://fonts.gstatic.com/s/roboto/v18/KFOlCnqEu92Fr1MmYUtvAw.ttf',
      '900italic': 'https://fonts.gstatic.com/s/roboto/v18/KFOjCnqEu92Fr1Mu51TLBBc9.ttf',
    },
  },
  {
    family: 'Roboto Mono',
    format: 'truetype',
    category: 'monospace',
    variants: ['100', '100italic', '300', '300italic', '400', '400italic', '500', '500italic', '700', '700italic'],
    version: 'v5',
    lastModified: '2017-10-10',
    files: {
      100: 'https://fonts.gstatic.com/s/robotomono/v5/L0x7DF4xlVMF-BfR8bXMIjAoq3o.ttf',
      '100italic': 'https://fonts.gstatic.com/s/robotomono/v5/L0xlDF4xlVMF-BfR8bXMIjhOkx6WXw.ttf',
      300: 'https://fonts.gstatic.com/s/robotomono/v5/L0xkDF4xlVMF-BfR8bXMIjDgiVq2.ttf',
      '300italic': 'https://fonts.gstatic.com/s/robotomono/v5/L0xmDF4xlVMF-BfR8bXMIjhOk9a0f7o.ttf',
      400: 'https://fonts.gstatic.com/s/robotomono/v5/L0x5DF4xlVMF-BfR8bXMIghM.ttf',
      '400italic': 'https://fonts.gstatic.com/s/robotomono/v5/L0x7DF4xlVMF-BfR8bXMIjhOq3o.ttf',
      500: 'https://fonts.gstatic.com/s/robotomono/v5/L0xkDF4xlVMF-BfR8bXMIjC4iFq2.ttf',
      '500italic': 'https://fonts.gstatic.com/s/robotomono/v5/L0xmDF4xlVMF-BfR8bXMIjhOk461f7o.ttf',
      700: 'https://fonts.gstatic.com/s/robotomono/v5/L0xkDF4xlVMF-BfR8bXMIjDwjlq2.ttf',
      '700italic': 'https://fonts.gstatic.com/s/robotomono/v5/L0xmDF4xlVMF-BfR8bXMIjhOk8azf7o.ttf',
    },
  },
  {
    family: 'Roboto Slab',
    format: 'truetype',
    category: 'serif',
    variants: ['100', '300', '400', '700'],
    // "subsets": ["latin-ext", "greek", "latin", "vietnamese", "cyrillic", "cyrillic-ext", "greek-ext"],
    version: 'v7',
    lastModified: '2017-10-11',
    files: {
      100: 'https://fonts.gstatic.com/s/robotoslab/v7/BngOUXZYTXPIvIBgJJSb6u-u5qA.ttf',
      300: 'https://fonts.gstatic.com/s/robotoslab/v7/BngRUXZYTXPIvIBgJJSb6u9mxICB.ttf',
      400: 'https://fonts.gstatic.com/s/robotoslab/v7/BngMUXZYTXPIvIBgJJSb6tfK.ttf',
      700: 'https://fonts.gstatic.com/s/robotoslab/v7/BngRUXZYTXPIvIBgJJSb6u92w4CB.ttf',
    },
  },
  {
    family: 'IBM Plex Sans',
    format: 'truetype',
    category: 'sans-serif',
    variants: [
      '100',
      '100italic',
      '200',
      '200italic',
      '300',
      '300italic',
      '400',
      '400italic',
      '500',
      '500italic',
      '600',
      '600italic',
      '700',
      '700italic',
    ],
    version: 'v3',
    lastModified: '2018-08-29',
    files: {
      100: 'https://fonts.gstatic.com/s/ibmplexsans/v3/zYX-KVElMYYaJe8bpLHnCwDKjbLeEA.ttf',
      '100italic': 'https://fonts.gstatic.com/s/ibmplexsans/v3/zYX8KVElMYYaJe8bpLHnCwDKhdTmdKZM.ttf',
      200: 'https://fonts.gstatic.com/s/ibmplexsans/v3/zYX9KVElMYYaJe8bpLHnCwDKjR7_MIY.ttf',
      '200italic': 'https://fonts.gstatic.com/s/ibmplexsans/v3/zYX7KVElMYYaJe8bpLHnCwDKhdTm2IdscQ.ttf',
      300: 'https://fonts.gstatic.com/s/ibmplexsans/v3/zYX9KVElMYYaJe8bpLHnCwDKjXr8MIY.ttf',
      '300italic': 'https://fonts.gstatic.com/s/ibmplexsans/v3/zYX7KVElMYYaJe8bpLHnCwDKhdTmvIRscQ.ttf',
      400: 'https://fonts.gstatic.com/s/ibmplexsans/v3/zYXgKVElMYYaJe8bpLHnCwDKtdY.ttf',
      '400italic': 'https://fonts.gstatic.com/s/ibmplexsans/v3/zYX-KVElMYYaJe8bpLHnCwDKhdTeEA.ttf',
      500: 'https://fonts.gstatic.com/s/ibmplexsans/v3/zYX9KVElMYYaJe8bpLHnCwDKjSL9MIY.ttf',
      '500italic': 'https://fonts.gstatic.com/s/ibmplexsans/v3/zYX7KVElMYYaJe8bpLHnCwDKhdTm5IVscQ.ttf',
      600: 'https://fonts.gstatic.com/s/ibmplexsans/v3/zYX9KVElMYYaJe8bpLHnCwDKjQ76MIY.ttf',
      '600italic': 'https://fonts.gstatic.com/s/ibmplexsans/v3/zYX7KVElMYYaJe8bpLHnCwDKhdTmyIJscQ.ttf',
      700: 'https://fonts.gstatic.com/s/ibmplexsans/v3/zYX9KVElMYYaJe8bpLHnCwDKjWr7MIY.ttf',
      '700italic': 'https://fonts.gstatic.com/s/ibmplexsans/v3/zYX7KVElMYYaJe8bpLHnCwDKhdTmrINscQ.ttf',
    },
  },
  {
    family: 'Poppins',
    format: 'truetype',
    category: 'sans-serif',
    variants: [
      '100',
      '100italic',
      '200',
      '200italic',
      '300',
      '300italic',
      '400',
      '400italic',
      '500',
      '500italic',
      '600',
      '600italic',
      '700',
      '700italic',
      '800',
      '800italic',
      '900',
      '900italic',
    ],
    // "subsets": ["devanagari", "latin-ext", "latin"],
    version: 'v5',
    lastModified: '2017-11-21',
    files: {
      100: 'https://fonts.gstatic.com/s/poppins/v5/pxiGyp8kv8JHgFVrLPTedw.ttf',
      '100italic': 'https://fonts.gstatic.com/s/poppins/v5/pxiAyp8kv8JHgFVrJJLmE3tF.ttf',
      200: 'https://fonts.gstatic.com/s/poppins/v5/pxiByp8kv8JHgFVrLFj_V1s.ttf',
      '200italic': 'https://fonts.gstatic.com/s/poppins/v5/pxiDyp8kv8JHgFVrJJLmv1plEA.ttf',
      300: 'https://fonts.gstatic.com/s/poppins/v5/pxiByp8kv8JHgFVrLDz8V1s.ttf',
      '300italic': 'https://fonts.gstatic.com/s/poppins/v5/pxiDyp8kv8JHgFVrJJLm21llEA.ttf',
      400: 'https://fonts.gstatic.com/s/poppins/v5/pxiEyp8kv8JHgFVrFJA.ttf',
      '400italic': 'https://fonts.gstatic.com/s/poppins/v5/pxiGyp8kv8JHgFVrJJLedw.ttf',
      500: 'https://fonts.gstatic.com/s/poppins/v5/pxiByp8kv8JHgFVrLGT9V1s.ttf',
      '500italic': 'https://fonts.gstatic.com/s/poppins/v5/pxiDyp8kv8JHgFVrJJLmg1hlEA.ttf',
      600: 'https://fonts.gstatic.com/s/poppins/v5/pxiByp8kv8JHgFVrLEj6V1s.ttf',
      '600italic': 'https://fonts.gstatic.com/s/poppins/v5/pxiDyp8kv8JHgFVrJJLmr19lEA.ttf',
      700: 'https://fonts.gstatic.com/s/poppins/v5/pxiByp8kv8JHgFVrLCz7V1s.ttf',
      '700italic': 'https://fonts.gstatic.com/s/poppins/v5/pxiDyp8kv8JHgFVrJJLmy15lEA.ttf',
      800: 'https://fonts.gstatic.com/s/poppins/v5/pxiByp8kv8JHgFVrLDD4V1s.ttf',
      '800italic': 'https://fonts.gstatic.com/s/poppins/v5/pxiDyp8kv8JHgFVrJJLm111lEA.ttf',
      900: 'https://fonts.gstatic.com/s/poppins/v5/pxiByp8kv8JHgFVrLBT5V1s.ttf',
      '900italic': 'https://fonts.gstatic.com/s/poppins/v5/pxiDyp8kv8JHgFVrJJLm81xlEA.ttf',
    },
  },
  {
    family: 'BioRhyme',
    format: 'truetype',
    category: 'serif',
    variants: ['200', '300', '400', '700', '800'],
    // "subsets": ["latin-ext", "latin"],
    version: 'v2',
    lastModified: '2017-10-10',
    files: {
      200: 'https://fonts.gstatic.com/s/biorhyme/v2/1cX3aULHBpDMsHYW_ESOjnGA.ttf',
      300: 'https://fonts.gstatic.com/s/biorhyme/v2/1cX3aULHBpDMsHYW_ETqjXGA.ttf',
      400: 'https://fonts.gstatic.com/s/biorhyme/v2/1cXwaULHBpDMsHYW_HxG.ttf',
      700: 'https://fonts.gstatic.com/s/biorhyme/v2/1cX3aULHBpDMsHYW_ET6inGA.ttf',
      800: 'https://fonts.gstatic.com/s/biorhyme/v2/1cX3aULHBpDMsHYW_ETmiXGA.ttf',
    },
  },
  {
    family: 'Archivo Narrow',
    format: 'truetype',
    category: 'sans-serif',
    variants: ['400', '400italic', '500', '500italic', '600', '600italic', '700', '700italic'],
    // "subsets": ["latin-ext", "latin"],
    version: 'v8',
    lastModified: '2017-10-10',
    files: {
      400: 'https://fonts.gstatic.com/s/archivonarrow/v8/tss0ApVBdCYD5Q7hcxTE1ArZ0Yb3.ttf',
      '400italic': 'https://fonts.gstatic.com/s/archivonarrow/v8/tss2ApVBdCYD5Q7hcxTE1ArZ0bb1iXk.ttf',
      500: 'https://fonts.gstatic.com/s/archivonarrow/v8/tss3ApVBdCYD5Q7hcxTE1ArZ0b4Dqlla.ttf',
      '500italic': 'https://fonts.gstatic.com/s/archivonarrow/v8/tssxApVBdCYD5Q7hcxTE1ArZ0bb1sY1Z-9c.ttf',
      600: 'https://fonts.gstatic.com/s/archivonarrow/v8/tss3ApVBdCYD5Q7hcxTE1ArZ0b4vrVla.ttf',
      '600italic': 'https://fonts.gstatic.com/s/archivonarrow/v8/tssxApVBdCYD5Q7hcxTE1ArZ0bb1saFe-9c.ttf',
      700: 'https://fonts.gstatic.com/s/archivonarrow/v8/tss3ApVBdCYD5Q7hcxTE1ArZ0b5LrFla.ttf',
      '700italic': 'https://fonts.gstatic.com/s/archivonarrow/v8/tssxApVBdCYD5Q7hcxTE1ArZ0bb1scVf-9c.ttf',
    },
  },
  {
    family: 'Libre Baskerville',
    format: 'truetype',
    category: 'serif',
    variants: ['400', '400italic', '700'],
    // "subsets": ["latin-ext", "latin"],
    version: 'v5',
    lastModified: '2017-10-10',
    files: {
      400: 'https://fonts.gstatic.com/s/librebaskerville/v5/kmKnZrc3Hgbbcjq75U4uslyuy4kn0pNe.ttf',
      '400italic': 'https://fonts.gstatic.com/s/librebaskerville/v5/kmKhZrc3Hgbbcjq75U4uslyuy4kn0qNcaxY.ttf',
      700: 'https://fonts.gstatic.com/s/librebaskerville/v5/kmKiZrc3Hgbbcjq75U4uslyuy4kn0qviTjYw.ttf',
    },
  },
  {
    family: 'Playfair Display',
    format: 'truetype',
    category: 'serif',
    variants: ['400', '400italic', '700', '700italic', '900', '900italic'],
    // "subsets": ["latin-ext", "latin", "vietnamese", "cyrillic"],
    version: 'v13',
    lastModified: '2017-11-07',
    files: {
      400: 'https://fonts.gstatic.com/s/playfairdisplay/v13/nuFiD-vYSZviVYUb_rj3ij__anPXPTs.ttf',
      '400italic': 'https://fonts.gstatic.com/s/playfairdisplay/v13/nuFkD-vYSZviVYUb_rj3ij__anPXDTnYhQ.ttf',
      700: 'https://fonts.gstatic.com/s/playfairdisplay/v13/nuFlD-vYSZviVYUb_rj3ij__anPXBYf9pWk.ttf',
      '700italic': 'https://fonts.gstatic.com/s/playfairdisplay/v13/nuFnD-vYSZviVYUb_rj3ij__anPXDTngOWwe4w.ttf',
      900: 'https://fonts.gstatic.com/s/playfairdisplay/v13/nuFlD-vYSZviVYUb_rj3ij__anPXBb__pWk.ttf',
      '900italic': 'https://fonts.gstatic.com/s/playfairdisplay/v13/nuFnD-vYSZviVYUb_rj3ij__anPXDTngAW4e4w.ttf',
    },
  },
  {
    family: 'Karla',
    format: 'truetype',
    category: 'sans-serif',
    variants: ['400', '400italic', '700', '700italic'],
    // "subsets": ["latin-ext", "latin"],
    version: 'v6',
    lastModified: '2017-10-10',
    files: {
      400: 'https://fonts.gstatic.com/s/karla/v6/qkBbXvYC6trAT4RS.ttf',
      '400italic': 'https://fonts.gstatic.com/s/karla/v6/qkBVXvYC6trAT7RQLtk.ttf',
      700: 'https://fonts.gstatic.com/s/karla/v6/qkBWXvYC6trAT7zuC_m-.ttf',
      '700italic': 'https://fonts.gstatic.com/s/karla/v6/qkBQXvYC6trAT7RQFmW7xL4.ttf',
    },
  },
  {
    family: 'Montserrat',
    format: 'truetype',
    category: 'sans-serif',
    variants: [
      '100',
      '100italic',
      '200',
      '200italic',
      '300',
      '300italic',
      '400',
      '400italic',
      '500',
      '500italic',
      '600',
      '600italic',
      '700',
      '700italic',
      '800',
      '800italic',
      '900',
      '900italic',
    ],
    // "subsets": ["latin-ext", "latin", "vietnamese", "cyrillic", "cyrillic-ext"],
    version: 'v12',
    lastModified: '2017-11-07',
    files: {
      100: 'https://fonts.gstatic.com/s/montserrat/v12/JTUQjIg1_i6t8kCHKm45_Qphzg.ttf',
      '100italic': 'https://fonts.gstatic.com/s/montserrat/v12/JTUOjIg1_i6t8kCHKm459WxZqi7j.ttf',
      200: 'https://fonts.gstatic.com/s/montserrat/v12/JTURjIg1_i6t8kCHKm45_aZA7g4.ttf',
      '200italic': 'https://fonts.gstatic.com/s/montserrat/v12/JTUPjIg1_i6t8kCHKm459WxZBg_D-w.ttf',
      300: 'https://fonts.gstatic.com/s/montserrat/v12/JTURjIg1_i6t8kCHKm45_cJD7g4.ttf',
      '300italic': 'https://fonts.gstatic.com/s/montserrat/v12/JTUPjIg1_i6t8kCHKm459WxZYgzD-w.ttf',
      400: 'https://fonts.gstatic.com/s/montserrat/v12/JTUSjIg1_i6t8kCHKm45xW4.ttf',
      '400italic': 'https://fonts.gstatic.com/s/montserrat/v12/JTUQjIg1_i6t8kCHKm459Wxhzg.ttf',
      500: 'https://fonts.gstatic.com/s/montserrat/v12/JTURjIg1_i6t8kCHKm45_ZpC7g4.ttf',
      '500italic': 'https://fonts.gstatic.com/s/montserrat/v12/JTUPjIg1_i6t8kCHKm459WxZOg3D-w.ttf',
      600: 'https://fonts.gstatic.com/s/montserrat/v12/JTURjIg1_i6t8kCHKm45_bZF7g4.ttf',
      '600italic': 'https://fonts.gstatic.com/s/montserrat/v12/JTUPjIg1_i6t8kCHKm459WxZFgrD-w.ttf',
      700: 'https://fonts.gstatic.com/s/montserrat/v12/JTURjIg1_i6t8kCHKm45_dJE7g4.ttf',
      '700italic': 'https://fonts.gstatic.com/s/montserrat/v12/JTUPjIg1_i6t8kCHKm459WxZcgvD-w.ttf',
      800: 'https://fonts.gstatic.com/s/montserrat/v12/JTURjIg1_i6t8kCHKm45_c5H7g4.ttf',
      '800italic': 'https://fonts.gstatic.com/s/montserrat/v12/JTUPjIg1_i6t8kCHKm459WxZbgjD-w.ttf',
      900: 'https://fonts.gstatic.com/s/montserrat/v12/JTURjIg1_i6t8kCHKm45_epG7g4.ttf',
      '900italic': 'https://fonts.gstatic.com/s/montserrat/v12/JTUPjIg1_i6t8kCHKm459WxZSgnD-w.ttf',
    },
  },
  {
    family: 'Proza Libre',
    format: 'truetype',
    category: 'sans-serif',
    variants: ['400', '400italic', '500', '500italic', '600', '600italic', '700', '700italic', '800', '800italic'],
    // "subsets": ["latin-ext", "latin"],
    version: 'v2',
    lastModified: '2017-10-10',
    files: {
      400: 'https://fonts.gstatic.com/s/prozalibre/v2/LYjGdGHgj0k1DIQRyUEyyHov.ttf',
      '400italic': 'https://fonts.gstatic.com/s/prozalibre/v2/LYjEdGHgj0k1DIQRyUEyyEotdN8.ttf',
      500: 'https://fonts.gstatic.com/s/prozalibre/v2/LYjbdGHgj0k1DIQRyUEyyELbV__f.ttf',
      '500italic': 'https://fonts.gstatic.com/s/prozalibre/v2/LYjZdGHgj0k1DIQRyUEyyEotTCvceJQ.ttf',
      600: 'https://fonts.gstatic.com/s/prozalibre/v2/LYjbdGHgj0k1DIQRyUEyyEL3UP_f.ttf',
      '600italic': 'https://fonts.gstatic.com/s/prozalibre/v2/LYjZdGHgj0k1DIQRyUEyyEotTAfbeJQ.ttf',
      700: 'https://fonts.gstatic.com/s/prozalibre/v2/LYjbdGHgj0k1DIQRyUEyyEKTUf_f.ttf',
      '700italic': 'https://fonts.gstatic.com/s/prozalibre/v2/LYjZdGHgj0k1DIQRyUEyyEotTGPaeJQ.ttf',
      800: 'https://fonts.gstatic.com/s/prozalibre/v2/LYjbdGHgj0k1DIQRyUEyyEKPUv_f.ttf',
      '800italic': 'https://fonts.gstatic.com/s/prozalibre/v2/LYjZdGHgj0k1DIQRyUEyyEotTH_ZeJQ.ttf',
    },
  },
  {
    family: 'Spectral',
    format: 'truetype',
    category: 'serif',
    variants: [
      '200',
      '200italic',
      '300',
      '300italic',
      '400',
      '400italic',
      '500',
      '500italic',
      '600',
      '600italic',
      '700',
      '700italic',
      '800',
      '800italic',
    ],
    // "subsets": ["latin-ext", "latin", "vietnamese", "cyrillic"],
    version: 'v4',
    lastModified: '2017-11-21',
    files: {
      200: 'https://fonts.gstatic.com/s/spectral/v4/rnCs-xNNww_2s0amA9v2s13G.ttf',
      '200italic': 'https://fonts.gstatic.com/s/spectral/v4/rnCu-xNNww_2s0amA9M8qrXHafM.ttf',
      300: 'https://fonts.gstatic.com/s/spectral/v4/rnCs-xNNww_2s0amA9uSsF3G.ttf',
      '300italic': 'https://fonts.gstatic.com/s/spectral/v4/rnCu-xNNww_2s0amA9M8qtHEafM.ttf',
      400: 'https://fonts.gstatic.com/s/spectral/v4/rnCr-xNNww_2s0amA-M-.ttf',
      '400italic': 'https://fonts.gstatic.com/s/spectral/v4/rnCt-xNNww_2s0amA9M8kn0.ttf',
      500: 'https://fonts.gstatic.com/s/spectral/v4/rnCs-xNNww_2s0amA9vKsV3G.ttf',
      '500italic': 'https://fonts.gstatic.com/s/spectral/v4/rnCu-xNNww_2s0amA9M8qonFafM.ttf',
      600: 'https://fonts.gstatic.com/s/spectral/v4/rnCs-xNNww_2s0amA9vmtl3G.ttf',
      '600italic': 'https://fonts.gstatic.com/s/spectral/v4/rnCu-xNNww_2s0amA9M8qqXCafM.ttf',
      700: 'https://fonts.gstatic.com/s/spectral/v4/rnCs-xNNww_2s0amA9uCt13G.ttf',
      '700italic': 'https://fonts.gstatic.com/s/spectral/v4/rnCu-xNNww_2s0amA9M8qsHDafM.ttf',
      800: 'https://fonts.gstatic.com/s/spectral/v4/rnCs-xNNww_2s0amA9uetF3G.ttf',
      '800italic': 'https://fonts.gstatic.com/s/spectral/v4/rnCu-xNNww_2s0amA9M8qt3AafM.ttf',
    },
  },
  {
    family: 'Domine',
    format: 'truetype',
    category: 'serif',
    variants: ['400', '700'],
    // "subsets": ["latin-ext", "latin"],
    version: 'v5',
    lastModified: '2017-10-10',
    files: {
      400: 'https://fonts.gstatic.com/s/domine/v5/L0x8DFMnlVwD4h3RvA.ttf',
      700: 'https://fonts.gstatic.com/s/domine/v5/L0x_DFMnlVwD4h3pAN-CTQ.ttf',
    },
  },
  {
    family: 'Crimson Text',
    format: 'truetype',
    category: 'serif',
    variants: ['400', '400italic', '600', '600italic', '700', '700italic'],
    // "subsets": ["latin"],
    version: 'v8',
    lastModified: '2017-10-10',
    files: {
      400: 'https://fonts.gstatic.com/s/crimsontext/v8/wlp2gwHKFkZgtmSR3NB0oRJvaA.ttf',
      '400italic': 'https://fonts.gstatic.com/s/crimsontext/v8/wlpogwHKFkZgtmSR3NB0oRJfaghW.ttf',
      600: 'https://fonts.gstatic.com/s/crimsontext/v8/wlppgwHKFkZgtmSR3NB0oRJXsCx2Cw.ttf',
      '600italic': 'https://fonts.gstatic.com/s/crimsontext/v8/wlprgwHKFkZgtmSR3NB0oRJfajCOD9NV.ttf',
      700: 'https://fonts.gstatic.com/s/crimsontext/v8/wlppgwHKFkZgtmSR3NB0oRJX1C12Cw.ttf',
      '700italic': 'https://fonts.gstatic.com/s/crimsontext/v8/wlprgwHKFkZgtmSR3NB0oRJfajDqDtNV.ttf',
    },
  },
  {
    family: 'Inknut Antiqua',
    format: 'truetype',
    category: 'serif',
    variants: ['300', '400', '500', '600', '700', '800', '900'],
    // "subsets": ["devanagari", "latin-ext", "latin"],
    version: 'v3',
    lastModified: '2017-10-09',
    files: {
      300: 'https://fonts.gstatic.com/s/inknutantiqua/v3/Y4GRYax7VC4ot_qNB4nYpBdaKU2vwrj5.ttf',
      400: 'https://fonts.gstatic.com/s/inknutantiqua/v3/Y4GSYax7VC4ot_qNB4nYpBdaKXUD.ttf',
      500: 'https://fonts.gstatic.com/s/inknutantiqua/v3/Y4GRYax7VC4ot_qNB4nYpBdaKU33w7j5.ttf',
      600: 'https://fonts.gstatic.com/s/inknutantiqua/v3/Y4GRYax7VC4ot_qNB4nYpBdaKU3bxLj5.ttf',
      700: 'https://fonts.gstatic.com/s/inknutantiqua/v3/Y4GRYax7VC4ot_qNB4nYpBdaKU2_xbj5.ttf',
      800: 'https://fonts.gstatic.com/s/inknutantiqua/v3/Y4GRYax7VC4ot_qNB4nYpBdaKU2jxrj5.ttf',
      900: 'https://fonts.gstatic.com/s/inknutantiqua/v3/Y4GRYax7VC4ot_qNB4nYpBdaKU2Hx7j5.ttf',
    },
  },
  {
    family: 'PT Sans',
    format: 'truetype',
    category: 'sans-serif',
    variants: ['400', '400italic', '700', '700italic'],
    // "subsets": ["latin-ext", "latin", "cyrillic", "cyrillic-ext"],
    version: 'v9',
    lastModified: '2017-10-11',
    files: {
      400: 'https://fonts.gstatic.com/s/ptsans/v9/jizaRExUiTo99u79P0U.ttf',
      '400italic': 'https://fonts.gstatic.com/s/ptsans/v9/jizYRExUiTo99u79D0eEwA.ttf',
      700: 'https://fonts.gstatic.com/s/ptsans/v9/jizfRExUiTo99u79B_mh4Ok.ttf',
      '700italic': 'https://fonts.gstatic.com/s/ptsans/v9/jizdRExUiTo99u79D0e8fOytKA.ttf',
    },
  },
  {
    family: 'PT Serif',
    format: 'truetype',
    category: 'serif',
    variants: ['400', '400italic', '700', '700italic'],
    // "subsets": ["latin-ext", "latin", "cyrillic", "cyrillic-ext"],
    version: 'v9',
    lastModified: '2017-10-11',
    files: {
      400: 'https://fonts.gstatic.com/s/ptserif/v9/EJRVQgYoZZY2vCFuvDFR.ttf',
      '400italic': 'https://fonts.gstatic.com/s/ptserif/v9/EJRTQgYoZZY2vCFuvAFTzro.ttf',
      700: 'https://fonts.gstatic.com/s/ptserif/v9/EJRSQgYoZZY2vCFuvAnt65qV.ttf',
      '700italic': 'https://fonts.gstatic.com/s/ptserif/v9/EJRQQgYoZZY2vCFuvAFT9gaQVy4.ttf',
    },
  },
  {
    family: 'Lato',
    format: 'truetype',
    category: 'sans-serif',
    variants: ['100', '100italic', '300', '300italic', '400', '400italic', '700', '700italic', '900', '900italic'],
    // "subsets": ["latin-ext", "latin"],
    version: 'v14',
    lastModified: '2017-10-11',
    files: {
      100: 'https://fonts.gstatic.com/s/lato/v14/S6u8w4BMUTPHh30wWw.ttf',
      '100italic': 'https://fonts.gstatic.com/s/lato/v14/S6u-w4BMUTPHjxsIPy-v.ttf',
      300: 'https://fonts.gstatic.com/s/lato/v14/S6u9w4BMUTPHh7USew8.ttf',
      '300italic': 'https://fonts.gstatic.com/s/lato/v14/S6u_w4BMUTPHjxsI9w2PHA.ttf',
      400: 'https://fonts.gstatic.com/s/lato/v14/S6uyw4BMUTPHvxk.ttf',
      '400italic': 'https://fonts.gstatic.com/s/lato/v14/S6u8w4BMUTPHjxswWw.ttf',
      700: 'https://fonts.gstatic.com/s/lato/v14/S6u9w4BMUTPHh6UVew8.ttf',
      '700italic': 'https://fonts.gstatic.com/s/lato/v14/S6u_w4BMUTPHjxsI5wqPHA.ttf',
      900: 'https://fonts.gstatic.com/s/lato/v14/S6u9w4BMUTPHh50Xew8.ttf',
      '900italic': 'https://fonts.gstatic.com/s/lato/v14/S6u_w4BMUTPHjxsI3wiPHA.ttf',
    },
  },
  {
    family: 'Cardo',
    format: 'truetype',
    category: 'serif',
    variants: ['400', '400italic', '700'],
    // "subsets": ["latin-ext", "greek", "latin", "greek-ext"],
    version: 'v9',
    lastModified: '2017-10-10',
    files: {
      400: 'https://fonts.gstatic.com/s/cardo/v9/wlp_gwjKBV1pqiv_.ttf',
      '400italic': 'https://fonts.gstatic.com/s/cardo/v9/wlpxgwjKBV1pqhv93IQ.ttf',
      700: 'https://fonts.gstatic.com/s/cardo/v9/wlpygwjKBV1pqhND-aQR.ttf',
    },
  },
  {
    family: 'Nunito Sans',
    format: 'truetype',
    category: 'sans-serif',
    variants: [
      '200',
      '200italic',
      '300',
      '300italic',
      '400',
      '400italic',
      '600',
      '600italic',
      '700',
      '700italic',
      '800',
      '800italic',
      '900',
      '900italic',
    ],
    // "subsets": ["latin-ext", "latin", "vietnamese"],
    version: 'v3',
    lastModified: '2017-10-10',
    files: {
      '200': 'https://fonts.gstatic.com/s/nunitosans/v3/pe03MImSLYBIv1o4X1M8cc9yAv5q.ttf',
      '200italic': 'https://fonts.gstatic.com/s/nunitosans/v3/pe01MImSLYBIv1o4X1M8cce4GxZrU1Q.ttf',
      '300': 'https://fonts.gstatic.com/s/nunitosans/v3/pe03MImSLYBIv1o4X1M8cc8WAf5q.ttf',
      '300italic': 'https://fonts.gstatic.com/s/nunitosans/v3/pe01MImSLYBIv1o4X1M8cce4G3JoU1Q.ttf',
      400: 'https://fonts.gstatic.com/s/nunitosans/v3/pe0qMImSLYBIv1o4X1M8cfe6.ttf',
      '400italic': 'https://fonts.gstatic.com/s/nunitosans/v3/pe0oMImSLYBIv1o4X1M8cce4I94.ttf',
      '600': 'https://fonts.gstatic.com/s/nunitosans/v3/pe03MImSLYBIv1o4X1M8cc9iB_5q.ttf',
      '600italic': 'https://fonts.gstatic.com/s/nunitosans/v3/pe01MImSLYBIv1o4X1M8cce4GwZuU1Q.ttf',
      '700': 'https://fonts.gstatic.com/s/nunitosans/v3/pe03MImSLYBIv1o4X1M8cc8GBv5q.ttf',
      '700italic': 'https://fonts.gstatic.com/s/nunitosans/v3/pe01MImSLYBIv1o4X1M8cce4G2JvU1Q.ttf',
      '800': 'https://fonts.gstatic.com/s/nunitosans/v3/pe03MImSLYBIv1o4X1M8cc8aBf5q.ttf',
      '800italic': 'https://fonts.gstatic.com/s/nunitosans/v3/pe01MImSLYBIv1o4X1M8cce4G35sU1Q.ttf',
      '900': 'https://fonts.gstatic.com/s/nunitosans/v3/pe03MImSLYBIv1o4X1M8cc8-BP5q.ttf',
      '900italic': 'https://fonts.gstatic.com/s/nunitosans/v3/pe01MImSLYBIv1o4X1M8cce4G1ptU1Q.ttf',
    },
  },
  {
    family: 'Neuton',
    format: 'truetype',
    category: 'serif',
    variants: ['200', '300', '400', '400italic', '700', '800'],
    // "subsets": ["latin-ext", "latin"],
    version: 'v10',
    lastModified: '2017-10-10',
    files: {
      200: 'https://fonts.gstatic.com/s/neuton/v10/UMBQrPtMoH62xUZKAKkfeg.ttf',
      300: 'https://fonts.gstatic.com/s/neuton/v10/UMBQrPtMoH62xUZKZKofeg.ttf',
      400: 'https://fonts.gstatic.com/s/neuton/v10/UMBTrPtMoH62xUZyyA.ttf',
      '400italic': 'https://fonts.gstatic.com/s/neuton/v10/UMBRrPtMoH62xUZCyog_.ttf',
      700: 'https://fonts.gstatic.com/s/neuton/v10/UMBQrPtMoH62xUZKdK0feg.ttf',
      800: 'https://fonts.gstatic.com/s/neuton/v10/UMBQrPtMoH62xUZKaK4feg.ttf',
    },
  },
  {
    family: 'Open Sans',
    format: 'truetype',
    category: 'sans-serif',
    variants: ['300', '300italic', '400', '400italic', '600', '600italic', '700', '700italic', '800', '800italic'],
    // "subsets": ["latin-ext", "greek", "latin", "vietnamese", "cyrillic", "cyrillic-ext", "greek-ext"],
    version: 'v15',
    lastModified: '2017-10-11',
    files: {
      300: 'https://fonts.gstatic.com/s/opensans/v15/mem5YaGs126MiZpBA-UN_r8-VQ.ttf',
      '300italic': 'https://fonts.gstatic.com/s/opensans/v15/memnYaGs126MiZpBA-UFUKWyV-hs.ttf',
      400: 'https://fonts.gstatic.com/s/opensans/v15/mem8YaGs126MiZpBA-U1Ug.ttf',
      '400italic': 'https://fonts.gstatic.com/s/opensans/v15/mem6YaGs126MiZpBA-UFUJ0e.ttf',
      600: 'https://fonts.gstatic.com/s/opensans/v15/mem5YaGs126MiZpBA-UNirk-VQ.ttf',
      '600italic': 'https://fonts.gstatic.com/s/opensans/v15/memnYaGs126MiZpBA-UFUKXGUehs.ttf',
      700: 'https://fonts.gstatic.com/s/opensans/v15/mem5YaGs126MiZpBA-UN7rg-VQ.ttf',
      '700italic': 'https://fonts.gstatic.com/s/opensans/v15/memnYaGs126MiZpBA-UFUKWiUOhs.ttf',
      800: 'https://fonts.gstatic.com/s/opensans/v15/mem5YaGs126MiZpBA-UN8rs-VQ.ttf',
      '800italic': 'https://fonts.gstatic.com/s/opensans/v15/memnYaGs126MiZpBA-UFUKW-U-hs.ttf',
    },
  },
  {
    family: 'Oswald',
    format: 'truetype',
    category: 'sans-serif',
    variants: ['200', '300', '400', '500', '600', '700'],
    // subsets: ["latin-ext", "latin", "vietnamese", "cyrillic"],
    version: 'v16',
    lastModified: '2017-11-21',
    files: {
      200: 'https://fonts.gstatic.com/s/oswald/v16/TK3hWkUHHAIjg75-1h4jvQ.ttf',
      300: 'https://fonts.gstatic.com/s/oswald/v16/TK3hWkUHHAIjg75-sh0jvQ.ttf',
      400: 'https://fonts.gstatic.com/s/oswald/v16/TK3iWkUHHAIjg75GHg.ttf',
      500: 'https://fonts.gstatic.com/s/oswald/v16/TK3hWkUHHAIjg75-6hwjvQ.ttf',
      600: 'https://fonts.gstatic.com/s/oswald/v16/TK3hWkUHHAIjg75-xhsjvQ.ttf',
      700: 'https://fonts.gstatic.com/s/oswald/v16/TK3hWkUHHAIjg75-ohojvQ.ttf',
    },
  },
  {
    family: 'Inconsolata',
    format: 'truetype',
    category: 'monospace',
    variants: ['400', '700'],
    // "subsets": ["latin-ext", "latin", "vietnamese"],
    version: 'v16',
    lastModified: '2017-10-10',
    files: {
      400: 'https://fonts.gstatic.com/s/inconsolata/v16/QldKNThLqRwH-OJ1UHjlKFle.ttf',
      700: 'https://fonts.gstatic.com/s/inconsolata/v16/QldXNThLqRwH-OJ1UHjlKGHiw41u.ttf',
    },
  },
  {
    family: 'Cabin',
    format: 'truetype',
    category: 'sans-serif',
    variants: ['400', '400italic', '500', '500italic', '600', '600italic', '700', '700italic'],
    // "subsets": ["latin-ext", "latin", "vietnamese"],
    version: 'v12',
    lastModified: '2017-10-10',
    files: {
      400: 'https://fonts.gstatic.com/s/cabin/v12/u-4x0qWljRw-Pe83.ttf',
      '400italic': 'https://fonts.gstatic.com/s/cabin/v12/u-4_0qWljRw-Pd81__g.ttf',
      500: 'https://fonts.gstatic.com/s/cabin/v12/u-480qWljRw-PdfD3Nhi.ttf',
      '500italic': 'https://fonts.gstatic.com/s/cabin/v12/u-460qWljRw-Pd81xwxhuyw.ttf',
      600: 'https://fonts.gstatic.com/s/cabin/v12/u-480qWljRw-Pdfv29hi.ttf',
      '600italic': 'https://fonts.gstatic.com/s/cabin/v12/u-460qWljRw-Pd81xyBmuyw.ttf',
      700: 'https://fonts.gstatic.com/s/cabin/v12/u-480qWljRw-PdeL2thi.ttf',
      '700italic': 'https://fonts.gstatic.com/s/cabin/v12/u-460qWljRw-Pd81x0Rnuyw.ttf',
    },
  },
  {
    family: 'Cormorant Garamond',
    format: 'truetype',
    category: 'serif',
    variants: ['300', '300italic', '400', '400italic', '500', '500italic', '600', '600italic', '700', '700italic'],
    version: 'v5',
    lastModified: '2017-11-21',
    files: {
      300: 'https://fonts.gstatic.com/s/cormorantgaramond/v5/co3YmX5slCNuHLi8bLeY9MK7whWMhyjQAllvuQ.ttf',
      '300italic': 'https://fonts.gstatic.com/s/cormorantgaramond/v5/co3WmX5slCNuHLi8bLeY9MK7whWMhyjYrEPjuw-N.ttf',
      400: 'https://fonts.gstatic.com/s/cormorantgaramond/v5/co3bmX5slCNuHLi8bLeY9MK7whWMhyjorg.ttf',
      '400italic': 'https://fonts.gstatic.com/s/cormorantgaramond/v5/co3ZmX5slCNuHLi8bLeY9MK7whWMhyjYrHtP.ttf',
      500: 'https://fonts.gstatic.com/s/cormorantgaramond/v5/co3YmX5slCNuHLi8bLeY9MK7whWMhyjQWlhvuQ.ttf',
      '500italic': 'https://fonts.gstatic.com/s/cormorantgaramond/v5/co3WmX5slCNuHLi8bLeY9MK7whWMhyjYrEO7ug-N.ttf',
      600: 'https://fonts.gstatic.com/s/cormorantgaramond/v5/co3YmX5slCNuHLi8bLeY9MK7whWMhyjQdl9vuQ.ttf',
      '600italic': 'https://fonts.gstatic.com/s/cormorantgaramond/v5/co3WmX5slCNuHLi8bLeY9MK7whWMhyjYrEOXvQ-N.ttf',
      700: 'https://fonts.gstatic.com/s/cormorantgaramond/v5/co3YmX5slCNuHLi8bLeY9MK7whWMhyjQEl5vuQ.ttf',
      '700italic': 'https://fonts.gstatic.com/s/cormorantgaramond/v5/co3WmX5slCNuHLi8bLeY9MK7whWMhyjYrEPzvA-N.ttf',
    },
  },
  {
    family: 'Raleway',
    format: 'truetype',
    category: 'sans-serif',
    variants: [
      '100',
      '100italic',
      '200',
      '200italic',
      '300',
      '300italic',
      '400',
      '400italic',
      '500',
      '500italic',
      '600',
      '600italic',
      '700',
      '700italic',
      '800',
      '800italic',
      '900',
      '900italic',
    ],
    // "subsets": ["latin-ext", "latin"],
    version: 'v12',
    lastModified: '2017-10-11',
    files: {
      100: 'https://fonts.gstatic.com/s/raleway/v12/1Ptsg8zYS_SKggPNwE4ISg.ttf',
      '100italic': 'https://fonts.gstatic.com/s/raleway/v12/1Ptqg8zYS_SKggPNyCgwLoFv.ttf',
      200: 'https://fonts.gstatic.com/s/raleway/v12/1Ptrg8zYS_SKggPNwOIpaqE.ttf',
      '200italic': 'https://fonts.gstatic.com/s/raleway/v12/1Ptpg8zYS_SKggPNyCgwgqBPBQ.ttf',
      300: 'https://fonts.gstatic.com/s/raleway/v12/1Ptrg8zYS_SKggPNwIYqaqE.ttf',
      '300italic': 'https://fonts.gstatic.com/s/raleway/v12/1Ptpg8zYS_SKggPNyCgw5qNPBQ.ttf',
      400: 'https://fonts.gstatic.com/s/raleway/v12/1Ptug8zYS_SKggPN-Co.ttf',
      '400italic': 'https://fonts.gstatic.com/s/raleway/v12/1Ptsg8zYS_SKggPNyCgISg.ttf',
      500: 'https://fonts.gstatic.com/s/raleway/v12/1Ptrg8zYS_SKggPNwN4raqE.ttf',
      '500italic': 'https://fonts.gstatic.com/s/raleway/v12/1Ptpg8zYS_SKggPNyCgwvqJPBQ.ttf',
      600: 'https://fonts.gstatic.com/s/raleway/v12/1Ptrg8zYS_SKggPNwPIsaqE.ttf',
      '600italic': 'https://fonts.gstatic.com/s/raleway/v12/1Ptpg8zYS_SKggPNyCgwkqVPBQ.ttf',
      700: 'https://fonts.gstatic.com/s/raleway/v12/1Ptrg8zYS_SKggPNwJYtaqE.ttf',
      '700italic': 'https://fonts.gstatic.com/s/raleway/v12/1Ptpg8zYS_SKggPNyCgw9qRPBQ.ttf',
      800: 'https://fonts.gstatic.com/s/raleway/v12/1Ptrg8zYS_SKggPNwIouaqE.ttf',
      '800italic': 'https://fonts.gstatic.com/s/raleway/v12/1Ptpg8zYS_SKggPNyCgw6qdPBQ.ttf',
      900: 'https://fonts.gstatic.com/s/raleway/v12/1Ptrg8zYS_SKggPNwK4vaqE.ttf',
      '900italic': 'https://fonts.gstatic.com/s/raleway/v12/1Ptpg8zYS_SKggPNyCgwzqZPBQ.ttf',
    },
  },
  {
    family: 'Anonymous Pro',
    format: 'truetype',
    category: 'monospace',
    variants: ['400', '400italic', '700', '700italic'],
    // "subsets": ["latin-ext", "greek", "latin", "cyrillic"],
    version: 'v11',
    lastModified: '2017-10-10',
    files: {
      400: 'https://fonts.gstatic.com/s/anonymouspro/v11/rP2Bp2a15UIB7Un-bOeISG3pLlw.ttf',
      '400italic': 'https://fonts.gstatic.com/s/anonymouspro/v11/rP2fp2a15UIB7Un-bOeISG3pHl428A.ttf',
      700: 'https://fonts.gstatic.com/s/anonymouspro/v11/rP2cp2a15UIB7Un-bOeISG3pFuAT0Ck.ttf',
      '700italic': 'https://fonts.gstatic.com/s/anonymouspro/v11/rP2ap2a15UIB7Un-bOeISG3pHl4OTCzc6A.ttf',
    },
  },
  {
    family: 'Arvo',
    format: 'truetype',
    category: 'serif',
    variants: ['400', '400italic', '700', '700italic'],
    // "subsets": ["latin"],
    version: 'v10',
    lastModified: '2017-10-10',
    files: {
      400: 'https://fonts.gstatic.com/s/arvo/v10/tDbD2oWUg0MKmSA.ttf',
      '400italic': 'https://fonts.gstatic.com/s/arvo/v10/tDbN2oWUg0MKqSIQ6A.ttf',
      700: 'https://fonts.gstatic.com/s/arvo/v10/tDbM2oWUg0MKoZw1yLQ.ttf',
      '700italic': 'https://fonts.gstatic.com/s/arvo/v10/tDbO2oWUg0MKqSIoVLHK9g.ttf',
    },
  },
  {
    family: 'Merriweather',
    format: 'truetype',
    category: 'serif',
    variants: ['300', '300italic', '400', '400italic', '700', '700italic', '900', '900italic'],
    // "subsets": ["latin-ext", "latin", "vietnamese", "cyrillic", "cyrillic-ext"],
    version: 'v19',
    lastModified: '2017-11-07',
    files: {
      300: 'https://fonts.gstatic.com/s/merriweather/v19/u-4n0qyriQwlOrhSvowK_l521wRpXw.ttf',
      '300italic': 'https://fonts.gstatic.com/s/merriweather/v19/u-4l0qyriQwlOrhSvowK_l5-eR7lXcf_.ttf',
      400: 'https://fonts.gstatic.com/s/merriweather/v19/u-440qyriQwlOrhSvowK_l5Oew.ttf',
      '400italic': 'https://fonts.gstatic.com/s/merriweather/v19/u-4m0qyriQwlOrhSvowK_l5-eSZJ.ttf',
      700: 'https://fonts.gstatic.com/s/merriweather/v19/u-4n0qyriQwlOrhSvowK_l52xwNpXw.ttf',
      '700italic': 'https://fonts.gstatic.com/s/merriweather/v19/u-4l0qyriQwlOrhSvowK_l5-eR71Wsf_.ttf',
      900: 'https://fonts.gstatic.com/s/merriweather/v19/u-4n0qyriQwlOrhSvowK_l52_wFpXw.ttf',
      '900italic': 'https://fonts.gstatic.com/s/merriweather/v19/u-4l0qyriQwlOrhSvowK_l5-eR7NWMf_.ttf',
    },
  },
  {
    family: 'Work Sans',
    format: 'truetype',
    category: 'sans-serif',
    variants: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
    // "subsets": ["latin-ext", "latin"],
    version: 'v3',
    lastModified: '2017-10-10',
    files: {
      100: 'https://fonts.gstatic.com/s/worksans/v3/QGYqz_wNahGAdqQ43Rh3H6Ds.ttf',
      200: 'https://fonts.gstatic.com/s/worksans/v3/QGYpz_wNahGAdqQ43Rh3s4HMnw.ttf',
      300: 'https://fonts.gstatic.com/s/worksans/v3/QGYpz_wNahGAdqQ43Rh314LMnw.ttf',
      400: 'https://fonts.gstatic.com/s/worksans/v3/QGYsz_wNahGAdqQ43RhPew.ttf',
      500: 'https://fonts.gstatic.com/s/worksans/v3/QGYpz_wNahGAdqQ43Rh3j4PMnw.ttf',
      600: 'https://fonts.gstatic.com/s/worksans/v3/QGYpz_wNahGAdqQ43Rh3o4TMnw.ttf',
      700: 'https://fonts.gstatic.com/s/worksans/v3/QGYpz_wNahGAdqQ43Rh3x4XMnw.ttf',
      800: 'https://fonts.gstatic.com/s/worksans/v3/QGYpz_wNahGAdqQ43Rh324bMnw.ttf',
      900: 'https://fonts.gstatic.com/s/worksans/v3/QGYpz_wNahGAdqQ43Rh3_4fMnw.ttf',
    },
  },
]
